version: "3.3"
services:
  api:
    build:
      context: "./api"
      # env_file: .env
    restart: unless-stopped
    environment:
      GATEWAY: ${GATEWAY}
    volumes:
      - ./api/:/api/
    # depends_on:
      # mysql:
      #   condition: service_healthy
      # minio:
      #   condition: service_started
    # links:
      # - mysql
      # - minio
    ports:
      - "8040:8040"
  frontend:
    build:
      context: "./frontend"
      # env_file: .env
    restart: unless-stopped
    volumes:
      - ./frontend/:/frontend/
    # depends_on:
      # mysql:
      #   condition: service_healthy
      # minio:
      #   condition: service_started
    # links:
      # - mysql
      # - minio
    ports:
      - "8080:8080"
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    # entrypoint:
    #   - ganache-cli
    #   - --port
    #   - '8545'

    